version: 2.1

orbs:
  node : circleci/node@5

jobs: test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: 
          name: Run tests
          command: npm test
      verify-client build:

      executor: node/default
      steps:
        - checkout
        - node/install-packages:
            pkg-manager: npm
        - run:
          
            command: npm run build

    deploy:
    docker:
    - image: cimg/base:current
    steps:
    -run:
        name: Deploy to Render 
        command: |
          echo "Deploying to Render"
          curl $RENDER_STAGING_DEPLOYHOOK
workflows:
  build-and-test:
    jobs:
      - test-node
      filters:
        branches:
          only:
            - main
      - verify-client-build:
        requires:
        - test-node
      - deploy:
          requires:
            - verify-client-build